accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings

from accounts.views import SignUpView, SignInView, NewPasswordResetView, NewPasswordResetDone, NewPasswordResetConfirmView, NewPasswordResetCompleteView

app_name = 'acc'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(),  name='signin'),
    path('signout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='signout'),
    path('reset_password/', NewPasswordResetView.as_view(),  name='reset_password'),
    path('password_reset/done/', NewPasswordResetDone.as_view(), name='password_reset_done'),
    path('reset_password/<uidb64>/<token>/', NewPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password/done/', NewPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food_delivery/', include('delivery_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User

        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from accounts.forms import UserRegisterForm


class SignUpView(CreateView):
    form_class = UserRegisterForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('acc:signin')


class SignInView(LoginView):
    redirect_authenticated_user = True
    template_name = 'accounts/signin.html'


class NewPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_email.html'
    success_url = reverse_lazy('acc:password_reset_done')


class NewPasswordResetDone(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class NewPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('acc:password_reset_complete')


class NewPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'

accounts/templates/accounts/password_reset_done.html
{% extends "layout/layout.html" %}

{% block title %}
  <title>Восстановление пароля</title>
  {% endblock %}

{% block main %}
    <div class="card">
        <div class="card-body">
        <h4 class="card-title">Письмо с инструкциями по восстановлению пароля отправлено</h4>
            <p>Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время. Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
        </div>
    </div>
    <p align="center">Вернуться назад? <a href="{{ request.META.HTTP_REFERER }}">Назад!</a></p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% extends "layout/layout.html" %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Восстановление пароля</title>
  {% endblock %}

{% block main %}
    <div class="card">
        <div class="card-body">
        <h4 class="card-title">Восстановление пароля</h4>
            <p>Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.</p>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Восстановить мой пароль</button>
            </form>
        </div>
    </div>
    <p align="center">Вернуться назад? <a href="{{ request.META.HTTP_REFERER }}">Назад!</a></p>
{% endblock %}

accounts/templates/accounts/signin.html
{% extends "layout/layout.html" %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Авторизация</title>
  {% endblock %}

{% block main %}
    <div class="card">
        <div class="card-body">
        <h4 class="card-title">Войдите в аккаунт</h4>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Войти</button>
            </form>
        </div>
    </div>
    <p align="center">Нет аккаунта? <a href="{% url 'acc:signup' %}">Зарегистрируйтесь!</a></p>
    <p align="center">Забыли пароль? <a href="{% url 'acc:reset_password' %}">Сбросьте пароль!</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "layout/layout.html" %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Регистрация</title>
  {% endblock %}

{% block main %}
    <div class="card">
        <div class="card-body">
        <h4 class="card-title">Создайте аккаунт</h4>
            <form method="post">
                {% csrf_token %}
                <table>{% crispy form %}</table>
                <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
            </form>
        </div>
    </div>
    <p align="center">Уже зарегистрированы? <a href="{% url 'acc:signin' %}">Войдите!</a></p>
{% endblock %}