conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food_delivery/', include('delivery_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery_app/urls.py
from django.urls import path

from delivery_app.views import IndexView, CategoryView, DishView, CartView, AddToCartFromDishView, \
    AddToCartFromCategoryView, RemoveFromCartView, CheckoutView, SuccessView, SearchResultsView, AllDishesView, \
    MyOrdersView, CartUpdateView, FeedBackView, ContactSuccessView

app_name = 'app'
urlpatterns = [
    path('categories/', IndexView.as_view(), name='index'),
    path('all_dishes/', AllDishesView.as_view(), name='all_dishes'),
    path('my_orders/', MyOrdersView.as_view(), name='my_orders'),
    path('category/<int:pk>/<slug>/', CategoryView.as_view(), name='category'),
    path('dishes/<int:pk>/<slug>/', DishView.as_view(), name='dish'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/change_quantity/<int:cart_id>/', CartUpdateView.as_view(), name='change_quantity'),
    path('cart/checkout/', CheckoutView.as_view(), name='checkout'),
    path('remove_from_cart/', RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('add_to_cart_from_category/<int:dish_id>/<slug>/', AddToCartFromDishView.as_view(), name='add_to_cart_from_dish'),
    path('add_to_cart_from_dish/<int:dish_id>/<slug>/', AddToCartFromCategoryView.as_view(), name='add_to_cart_from_category'),
    path('success/', SuccessView.as_view(), name='success'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('contact/', FeedBackView.as_view(), name='contact'),
    path('contact/success/', ContactSuccessView.as_view(), name='contact_success'),
]

delivery_app/forms.py
from django import forms

from delivery_app.models import Cart, Order
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('payment_method', 'user_phone', 'address', 'user_comment', )

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Fieldset(
                '',
                'payment_method',
                'user_phone',
                'address',
                'user_comment',
            ),
            ButtonHolder(Submit('submit', 'Оформить заказ'))
        )


class CartForm(forms.ModelForm):

    class Meta:
        model = Cart
        fields = ('count_of_dishes',)

    def __init__(self, *args, **kwargs):
        super(CartForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Fieldset(
                '',
                'count_of_dishes',
            ),
            ButtonHolder(Submit('submit', 'Добавить блюдо'))
        )


class UpdateCartForm(forms.ModelForm):

    class Meta:
        model = Cart
        fields = ('count_of_dishes',)

    def __init__(self, *args, **kwargs):
        super(UpdateCartForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Fieldset(
                '',
                'count_of_dishes',
            ),
            ButtonHolder(Submit('submit', 'Изменить количество'))
        )


class FeedBackForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'name',
            'placeholder': "Ваше имя"
        })
    )
    email = forms.CharField(
        max_length=100,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'id': 'email',
            'placeholder': "Ваша почта"
        })
    )
    subject = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'subject',
            'placeholder': "Тема"
        })
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control md-textarea',
            'id': 'message',
            'rows': 2,
            'placeholder': "Ваше сообщение"
        })
    )

delivery_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import View
from django.views.generic import DeleteView
from django.views.generic.edit import CreateView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.timezone import now
from django.db.models import Q
from django.views.generic import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail, BadHeaderError

from delivery_app.models import Category, Dish, Cart, Order, Logo
from delivery_app.forms import CartForm, OrderForm, UpdateCartForm, FeedBackForm
from conf.settings import EMAIL_HOST_USER


class IndexView(View):
    """Стартовая страница с категориями блюд"""
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        paginator = Paginator(categories, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        logo = get_object_or_404(Logo, name='Берёзка')
        return render(request, 'delivery_app/index.html', {'page_obj': page_obj, 'logo': logo})


class AllDishesView(View):
    """Страница со всеми блюдами"""
    def get(self, request, *args, **kwargs):
        dishes = Dish.objects.all()
        paginator = Paginator(dishes, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        logo = get_object_or_404(Logo, name='Берёзка')
        return render(request, 'delivery_app/dish_list.html', {'page_obj': page_obj, 'logo': logo})


class MyOrdersView(View):
    """Все заказы пользователя"""
    def get(self, request, *args, **kwargs):
        pk_user = self.request.user.pk
        orders = Order.objects.filter(owner__id=pk_user)
        paginator = Paginator(orders, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'delivery_app/orders_list.html', {'page_obj': page_obj, 'count': len(orders)})


class CategoryView(LoginRequiredMixin, View):
    """Страница с блюдами, относящимся к определенной категории"""
    login_url = 'acc:signin'

    def get(self, request, slug, *args, **kwargs):
        dishes = Dish.objects.filter(category_id=self.kwargs['pk'], category__url_category=self.kwargs['slug'])
        category = get_object_or_404(Category, id=self.kwargs['pk'])
        paginator = Paginator(dishes, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'delivery_app/category_list.html', {'page_obj': page_obj, 'category': category})


class DishView(LoginRequiredMixin, View):
    """Страница с конкретным блюдом"""
    login_url = 'acc:signin'

    def get(self, request, slug, *args, **kwargs):
        dish = get_object_or_404(Dish, id=self.kwargs['pk'])
        return render(request, 'delivery_app/dish.html', {'dish': dish})


class CartView(LoginRequiredMixin, View):
    """Страница с отображением содержимого в корзине"""
    login_url = 'acc:signin'

    def get(self, request, *args, **kwargs):
        pk_user = self.request.user.pk
        cart = Cart.objects.filter(user__id=pk_user, active_status=True)
        order_price = 0
        for el in cart:
            count_price = el.dish.price * el.count_of_dishes
            order_price += count_price
        return render(request, 'delivery_app/cart.html', {'cart': cart, 'order_price': order_price})


class CartUpdateView(LoginRequiredMixin, UpdateView):
    """Изменение количества блюд в заказе в корзине"""
    login_url = 'acc:signin'
    template_name = 'delivery_app/change_in_cart.html'
    model = Cart
    form_class = UpdateCartForm

    def get_context_data(self, **kwargs):
        context = super(CartUpdateView, self).get_context_data(**kwargs)
        context['cart'] = get_object_or_404(Cart, pk=self.kwargs['cart_id'])
        return context

    def get_object(self, queryset=None):
        return self.model.objects.get(id=self.kwargs['cart_id'])

    def get_success_url(self):
        return reverse("app:cart")


class CheckoutView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Оформление заказа"""
    login_url = 'accounts:login'
    success_message = 'Новый заказ!'
    template_name = 'delivery_app/checkout.html'
    model = Order
    form_class = OrderForm

    def form_valid(self, form):
        form.instance.order_creation_time = now()
        form.instance.owner = self.request.user
        cart = Cart.objects.filter(user__id=self.request.user.pk, active_status=True)
        list_of_dishes = ''
        count = 1
        order_price = 0
        for el in cart:
            list_of_dishes += f'{count}) Блюдо: {el.dish.title}, цена: {el.dish.price} руб., количество: {el.count_of_dishes} шт.\n'
            order_price += el.dish.price * el.count_of_dishes
            Cart.objects.filter(pk=el.pk).update(active_status=False)
            count += 1
        list_of_dishes += f'Общая стоимость заказа составляет: {order_price} руб.'
        form.instance.list_of_dishes = list_of_dishes
        return super(CheckoutView, self).form_valid(form)

    def get_success_url(self):
        return reverse('app:success')


class AddToCartFromDishView(LoginRequiredMixin, CreateView):
    """Добавление блюда в корзину для заказа со страницы 'Блюдо'"""
    login_url = 'accounts:login'
    template_name = 'delivery_app/adding_to_cart.html'
    model = Cart
    form_class = CartForm

    def form_valid(self, form):
        form.instance.published_at = now()
        form.instance.user = self.request.user
        form.instance.dish = get_object_or_404(Dish, pk=self.kwargs['dish_id'])
        cart = Cart.objects.filter(user__id=self.request.user.pk, active_status=True, dish__id=self.kwargs['dish_id'])
        total = sum([el.count_of_dishes for el in cart])
        if len(cart) > 0:
            Cart.objects.filter(dish__title=cart.first().dish.title).delete()
            form.instance.count_of_dishes += total
        return super(AddToCartFromDishView, self).form_valid(form)

    def get_success_url(self):
        dish_pk = get_object_or_404(Dish, pk=self.kwargs['dish_id']).pk
        dish_slug = get_object_or_404(Dish, pk=self.kwargs['dish_id']).url_dish
        return reverse('app:dish', args=[dish_pk, dish_slug])


class AddToCartFromCategoryView(LoginRequiredMixin, CreateView):
    """Добавление блюда в корзину для заказа со страницы 'Категория'"""
    login_url = 'accounts:login'
    template_name = 'delivery_app/adding_to_cart.html'
    model = Cart
    form_class = CartForm

    def form_valid(self, form):
        form.instance.published_at = now()
        form.instance.user = self.request.user
        form.instance.dish = get_object_or_404(Dish, pk=self.kwargs['dish_id'])
        cart = Cart.objects.filter(user__id=self.request.user.pk, active_status=True, dish__id=self.kwargs['dish_id'])
        total = sum([el.count_of_dishes for el in cart])
        if len(cart) > 0:
            Cart.objects.filter(dish__title=cart.first().dish.title).delete()
            form.instance.count_of_dishes += total
        return super(AddToCartFromCategoryView, self).form_valid(form)

    def get_success_url(self):
        category_obj_pk = get_object_or_404(Dish, pk=self.kwargs['dish_id']).category.pk
        category_obj_slug = get_object_or_404(Dish, pk=self.kwargs['dish_id']).category.url_category
        return reverse('app:category', args=[category_obj_pk, category_obj_slug])


class RemoveFromCartView(LoginRequiredMixin, DeleteView):
    """Удаление блюда из корзины"""
    login_url = 'acc:signin'
    model = Cart

    def get_queryset(self):
        owner = self.request.user.pk
        variants = [int(i) for i in self.request.POST.getlist('variant')]
        return self.model.objects.filter(user__id=owner, id__in=variants)

    def get_object(self, queryset=None):
        return self.get_queryset()

    def get_success_url(self):
        return reverse('app:cart')


class SuccessView(LoginRequiredMixin, View):
    """Страница с благодарностью за заказ"""
    login_url = 'acc:signin'

    def get(self, request, *args, **kwargs):
        return render(request, 'delivery_app/success.html', context={'title': 'Спасибо'})


class SearchResultsView(View):
    """Поиск блюда или категории"""

    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        if query and query != '':
            dish_results = Dish.objects.filter(Q(title__icontains=query) | Q(description_dish__icontains=query) | Q(title__icontains=query.title()) | Q(description_dish__icontains=query.title()))
            category_results = Category.objects.filter(Q(title__icontains=query) | Q(description_category__icontains=query) | Q(title__icontains=query.title()) | Q(description_category__icontains=query.title()))
            all_things = list(dish_results) + list(category_results)
            sorted_things = sorted(all_things, key=lambda x: x.title)
            paginator = Paginator(sorted_things, 6)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            return render(request, 'delivery_app/search.html', context={'title': 'Поиск', 'results': page_obj, 'count': paginator.count})
        return HttpResponseRedirect(reverse('app:index'))


class FeedBackView(LoginRequiredMixin, View):
    """Обратная связь от клиента"""
    login_url = 'acc:signin'

    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        return render(request, 'delivery_app/contact.html', context={'form': form})

    def post(self, request, *args, **kwargs):
        form = FeedBackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['email']

delivery_app/templates/delivery_app/adding_to_cart.html
{% extends "base/basic.html" %}

{% block title %}Добавление в корзину | Березка{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <hr>
            <ol class="breadcrumb">
            <h4 class="breadcrumb-item">Добавить в корзину</h4>
            <h4 class="breadcrumb-item active" aria-current="page"><a href="{{ request.META.HTTP_REFERER }}">Назад</a></h4>
            </ol>
            <hr>
        </div>
    </div>
    <div class="col-lg-2">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>



{% endblock %}

delivery_app/templates/delivery_app/cart.html
{% extends "base/basic.html" %}

{% block title %}Корзина | Березка{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <hr>
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Корзина</li>
                <li class="breadcrumb-item">Ваш заказ:</li>
            </ol>
            <hr>
        </div>
    </div>
        {% if cart %}
        <form method="post" action="{% url 'app:remove_from_cart' %}">
        {% csrf_token %}
            {% for el in cart %}
            <input type="checkbox" name="variant{{ forloop.parentloop.counter }}" id="variant{{ forloop.counter }}" value="{{ el.pk }}" />
            <label for="variant{{ forloop.counter }}">
                <p class="mr-auto p-2 lead">{{ el.dish.title }}. Цена: {{ el.dish.price }} руб.<a href="{% url 'app:change_quantity' el.pk %}" name='post' class="mr-auto p-2 lead">Количество: {{ el.count_of_dishes }} шт.</a></p>
            </label>
            <br/>
        <br>
            {% endfor %}
            <input type="submit" class="btn btn-sm btn-outline-secondary" value="Удалить блюдо">
        </form>
        <hr>
        <h5>Общая стоимость заказа составляет: {{ order_price }} руб.</h5>
        <hr>
        <a href="{% url 'app:checkout' %}" name='post' class="btn btn-sm btn-outline-secondary">Оформить заказ</a>
        {% else %}
            <h5>У вас еще нет товара в корзине. Добавьте товар.</h5>
        {% endif %}

</div>
</div>

{% endblock %}

delivery_app/templates/delivery_app/category_list.html
{% extends "base/basic.html" %}

{% block title %}Выбранная категория | Березка{% endblock %}

{% block content %}
  <main class="container mt-3">
    <section class="mt-5 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Категория "{{ category.title }}"</h2>
      <div class="row mb-0">

      {% for dish in page_obj %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <a href="{% url 'app:dish' dish.pk dish.url_dish %}"><img src="{{ dish.image_dish.url }}" alt="" class="card-img-top"></a>
              <div class="card-body">
                <h4 class="card-title">{{ dish.title }}</h4>
                <h4 class="card-title">{{ dish.price }},00 руб.</h4>

                <br>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'app:dish' dish.pk dish.url_dish %}" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                  </div>
                </div>
                <br>
                <a href="{% url 'app:add_to_cart_from_category' dish.pk dish.url_dish %}" name='post' class="btn btn-sm btn-outline-secondary">Добавить в корзину</a>
              </div>
            </div>
          </div>

      {% endfor %}

      </div>
    </section>

  </main>
{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Предыдущая</a>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="#" tabindex="-1">Предыдущая</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if i == page_obj.number %}
          <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Следующая</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <br>
{% endblock %}

delivery_app/templates/delivery_app/change_in_cart.html
{% extends "base/basic.html" %}

{% block title %}Добавление в корзину | Березка{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <hr>
            <ol class="breadcrumb">
            <h4 class="breadcrumb-item">Изменить количество</h4>
            <h4 class="breadcrumb-item active" aria-current="page"><a href="{{ request.META.HTTP_REFERER }}">Назад</a></h4>
            </ol>
            <hr>
        </div>
    </div>
    <div class="col-lg-2">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>

{% endblock %}

delivery_app/templates/delivery_app/checkout.html
{% extends "base/basic.html" %}

{% block title %}Оформление заказа | Березка{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <hr>
            <ol class="breadcrumb">
            <h4 class="breadcrumb-item">Оформление заказа</h4>
            <h4 class="breadcrumb-item active" aria-current="page"><a href="{% url 'app:cart' %}">Назад</a></h4>
            </ol>
            <hr>
        </div>
    </div>
    <div class="col-lg-5">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>

{% endblock %}

delivery_app/templates/delivery_app/contact.html
{% extends "base/basic.html" %}

{% block title %}Обратная связь | Березка{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <nav aria-label="breadcrumb" class="mt-4">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Отзыв</li>
                    <li class="breadcrumb-item active" aria-current="page"><a href="{{ request.META.HTTP_REFERER }}">Назад</a></li>
                </ol>
            </nav>
            <p class="lead">Чтобы связаться с нами заполните форму обратной связи</p>
            {{ hello.q }}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form name="contact-form" method="post" action="{% url 'app:contact' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="name" class="sr-only">Ваше имя</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="email" class="sr-only">Ваша почта</label>
                            {{ form.email }}
                        </div>
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <label for="subject" class="sr-only">Тема</label>
                            {{ form.subject }}
                        </div>
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col-md-12">
                        <div class="md-form">
                            <label for="message" class="sr-only">Ваше сообщение</label>
                            {{ form.message }}
                        </div>
                    </div>
                </div>
                <div class="text-center text-md-left mt-3">
                    <button class="btn btn-primary" type="submit">Отправить</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

delivery_app/templates/delivery_app/contact_success.html
{% extends "base/basic.html" %}

{% block title %}Спасибо! | Березка{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <hr>
            <p class="lead">Ваше письмо отправлено. Спасибо!</p>
            <hr>
        </div>
    </div>
</div>

{% endblock %}

delivery_app/templates/delivery_app/dish.html
{% extends "base/basic.html" %}

{% block title %}{{ dish.title }} | Березка{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <hr>
            <ol class="breadcrumb">
                <h4 class="breadcrumb-item">{{ dish.title|safe }}</h4>
                <h4 class="breadcrumb-item active" aria-current="page"><a href="{{ request.META.HTTP_REFERER }}">Назад</a></h4>
            </ol>
            <hr>
            <img class="img-fluid rounded " src="{{ dish.image_dish.url }}" alt="">
            <hr>
            <div class="mr-auto p-2 lead">{{ dish.description_dish|safe }}</div>
            <hr>
            <div class="mr-auto p-2 lead">Цена: {{ dish.price }},00 руб.</div>
            <hr>
        </div>
    </div>
        <a href="{% url 'app:add_to_cart_from_dish' dish.pk dish.url_dish %}" name='post' class="btn btn-sm btn-outline-secondary">Добавить в корзину</a>
    <hr>
</div>
</div>

{% endblock %}

delivery_app/templates/delivery_app/dish_list.html
{% extends "base/basic.html" %}

{% block title %}Все блюда | Березка{% endblock %}

{% block content %}

<main class="container mt-3">

    <section>
      <hr>
      <h2 class="h2 font-weight-normal text-center mb-5">Доставка еды из кафе<br><br><img src="{{ logo.image_category.url }}" width="250" height="200"></h2>
<!--      <div class="row">-->
<!--        <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">-->

<!--          <form class="form-inline mb-3" action="{% url 'app:search_results' %}" method="get" enctype="multipart/form-data">-->
<!--          <div class="form-group col-8 col-md-10 pl-0">-->
<!--            <input class="form-control w-100" name="q" type="text" placeholder="Найти блюдо или категорию"  aria-label="Найти блюдо или категорию">-->
<!--          </div>-->
<!--          <div class="form-group col-4 col-md-2 pl-0">-->
<!--            <button class="btn btn-primary w-100" type="submit">Найти</button>-->
<!--          </div>-->
<!--        </form>-->
<!--        </div>-->
<!--      </div>-->
      <hr>
    </section>
  <br>

        <div class="row">
        <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">
          <form class="form-inline mb-3" action="{% url 'app:search_results' %}" method="get" enctype="multipart/form-data">
          <div class="form-group col-8 col-md-10 pl-0">
            <input class="form-control w-100" name="q" type="text" placeholder="Поиск блюда или категории"  aria-label="Поиск блюда или категории">
          </div>
          <div class="form-group col-4 col-md-2 pl-0">
            <button class="btn btn-primary w-100" type="submit">Найти</button>
          </div>
        </form>
        </div>
      </div>

    <section class="mt-2 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Все блюда:</h2>
      <div class="row mb-0">

      {% for dish in page_obj %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <a href="{% url 'app:dish' dish.pk dish.url_dish %}"><img src="{{ dish.image_dish.url }}" alt="" class="card-img-top"></a>
              <div class="card-body">
                <h4 class="card-title">{{ dish.title }}</h4>
                <h4 class="card-title">{{ dish.price }},00 руб.</h4>

                <br>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'app:dish' dish.pk dish.url_dish %}" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                  </div>
                </div>
                <br>
                <a href="{% url 'app:add_to_cart_from_category' dish.pk dish.url_dish %}" name='post' class="btn btn-sm btn-outline-secondary">Добавить в корзину</a>
              </div>
            </div>
          </div>

      {% endfor %}

      </div>
    </section>

{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Предыдущая</a>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="#" tabindex="-1">Предыдущая</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        {% if i == page_obj.number %}
          <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Следующая</a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <br>
{% endblock %}